# Generated by Django 2.0 on 2018-10-17 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Music', '0007_auto_20181017_0815'),
        ('User', '0003_user_reviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=512)),
                ('mtype', models.IntegerField(choices=[(0, '恭喜！你推荐的《%s》已被采纳，将作为%s的日推歌曲。'), (1, '对不起，你推荐的《%s》没有被采纳，原因为：%s。'), (2, '你审核通过的歌曲《%s》因为系统原因无法加入日推，请联系管理员，谢谢。')], default=None)),
                ('has_read', models.BooleanField(default=False)),
                ('re_music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.Music')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
        ),
    ]
