# Generated by Django 2.1.1 on 2018-10-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='歌曲名')),
                ('singer', models.CharField(max_length=100, verbose_name='歌手')),
                ('cover', models.CharField(max_length=1024, verbose_name='封面')),
                ('total_comment', models.IntegerField(default=0, verbose_name='评论总数')),
            ],
        ),
    ]
