# Generated by Django 2.0 on 2018-10-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='netease_id',
            field=models.IntegerField(default=0, verbose_name='网易云歌曲ID'),
        ),
    ]
