# Generated by Django 2.0 on 2018-10-17 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('Music', '0002_music_netease_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='create_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='music',
            name='last_update_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='music',
            name='re_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='User.User'),
        ),
        migrations.AddField(
            model_name='music',
            name='status',
            field=models.IntegerField(choices=[(0, 'under consider'), (1, 'accepted'), (2, 'refused')], default=0),
        ),
        migrations.AddField(
            model_name='music',
            name='updated_total_comment',
            field=models.IntegerField(default=0),
        ),
    ]
