# Generated by Django 2.0 on 2018-10-17 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_auto_20181017_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='re_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='recommend_user', to='User.User'),
        ),
    ]
