# Generated by Django 2.0 on 2018-10-17 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_reviewer'),
        ('Music', '0004_auto_20181017_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='consider_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='consider_user', to='User.User'),
        ),
    ]
