# Generated by Django 2.0 on 2018-10-17 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0005_music_consider_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='consider_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='consider_user', to='User.User'),
        ),
    ]
