# Generated by Django 2.0 on 2018-10-17 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0006_auto_20181017_0631'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_e', models.DateField(default=None, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='music',
            name='re_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommend_user', to='User.User'),
        ),
        migrations.AddField(
            model_name='dailyrecommend',
            name='re_music',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Music.Music'),
        ),
    ]
