# Generated by Django 2.0 on 2018-10-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='str_id',
            field=models.CharField(default=None, max_length=6, unique=True),
        ),
    ]
